# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestlogin2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testlogin2(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1522, 819)
    self.driver.find_element(By.ID, "email_login").click()
    self.driver.find_element(By.ID, "email_login").send_keys("super@gmail.com")
    self.driver.find_element(By.ID, "password_login").click()
    self.driver.find_element(By.ID, "password_login").send_keys("123")
    self.driver.find_element(By.ID, "log").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".btn-primary:nth-child(1)")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".menu-item:nth-child(3) > h3").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".profile_img > img")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Reunion").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu-item:nth-child(8) > h3").click()
    elements = self.driver.find_elements(By.ID, "log")
    assert len(elements) > 0
  
