"""Family Following Table

Revision ID: 14105c7cda18
Revises: 7fcb2ec6bbd4
Create Date: 2024-04-27 12:35:36.327653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14105c7cda18'
down_revision = '7fcb2ec6bbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FamilyFollowing',
    sa.Column('FollowingFamilyId', sa.Integer(), nullable=False),
    sa.Column('FollowedFamilyId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FollowedFamilyId'], ['family.id'], ),
    sa.ForeignKeyConstraint(['FollowingFamilyId'], ['family.id'], ),
    sa.PrimaryKeyConstraint('FollowingFamilyId', 'FollowedFamilyId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FamilyFollowing')
    # ### end Alembic commands ###
