"""adding profile photo column to family

Revision ID: 26d207b286d6
Revises: e4f4076e0560
Create Date: 2024-05-07 12:02:43.291202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26d207b286d6'
down_revision = 'e4f4076e0560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profilephoto', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_column('profilephoto')
    # ### end Alembic commands ###
