"""user table

Revision ID: 41173ba0de4c
Revises: 62372ae2209f
Create Date: 2024-04-27 12:23:43.422706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41173ba0de4c'
down_revision = '62372ae2209f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('FirstName', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('Gender', sa.Boolean(), nullable=False),
    sa.Column('Birthdate', sa.Date(), nullable=False),
    sa.Column('FamilyID', sa.Integer(), nullable=False),
    sa.Column('FamilyRole', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['FamilyID'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_FamilyID'), ['FamilyID'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_FamilyID'))

    op.drop_table('user')
    # ### end Alembic commands ###
