"""Content Table

Revision ID: 67e32639d0ff
Revises: 41173ba0de4c
Create Date: 2024-04-27 12:24:56.512963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e32639d0ff'
down_revision = '41173ba0de4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.Column('Type', sa.Boolean(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_userId'), ['userId'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_userId'))
        batch_op.drop_index(batch_op.f('ix_content_timestamp'))

    op.drop_table('content')
    # ### end Alembic commands ###
