"""photos table

Revision ID: 7fcb2ec6bbd4
Revises: 67e32639d0ff
Create Date: 2024-04-27 12:34:09.258530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcb2ec6bbd4'
down_revision = '67e32639d0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentphotos',
    sa.Column('contentId', sa.Integer(), nullable=False),
    sa.Column('photoUrl', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['contentId'], ['content.id'], ),
    sa.PrimaryKeyConstraint('contentId', 'photoUrl')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contentphotos')
    # ### end Alembic commands ###
