"""FamilyFollowing Table

Revision ID: 905c1fe380e5
Revises: bec6c72ef03a
Create Date: 2024-04-28 14:42:03.954841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '905c1fe380e5'
down_revision = 'bec6c72ef03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FamilyFollowing',
    sa.Column('FollowingFamilyId', sa.Integer(), nullable=False),
    sa.Column('FollowedFamilyId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FollowedFamilyId'], ['family.id'], ),
    sa.ForeignKeyConstraint(['FollowingFamilyId'], ['family.id'], ),
    sa.PrimaryKeyConstraint('FollowingFamilyId', 'FollowedFamilyId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FamilyFollowing')
    # ### end Alembic commands ###
