"""last table

Revision ID: 9dbc37c8c1b8
Revises: c7235f3ef8db
Create Date: 2024-04-27 12:44:14.817868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dbc37c8c1b8'
down_revision = 'c7235f3ef8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FamilyPendingRequests',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('FamilyId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('UserId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userlikedcontent',
    sa.Column('UserId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ContentId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ContentId'], ['content.id'], name='userlikedcontent_ibfk_1'),
    sa.ForeignKeyConstraint(['UserId'], ['user.id'], name='userlikedcontent_ibfk_2'),
    sa.PrimaryKeyConstraint('UserId', 'ContentId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('familyfollowing',
    sa.Column('FollowingFamilyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FollowedFamilyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['FollowedFamilyId'], ['family.id'], name='familyfollowing_ibfk_1'),
    sa.ForeignKeyConstraint(['FollowingFamilyId'], ['family.id'], name='familyfollowing_ibfk_2'),
    sa.PrimaryKeyConstraint('FollowingFamilyId', 'FollowedFamilyId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('UserLikedContent')
    op.drop_table('FamilyPendingRequests')
    op.drop_table('FamilyFollowing')
    # ### end Alembic commands ###
