"""UserLikedContent table

Revision ID: bec6c72ef03a
Revises: d2af900ee226
Create Date: 2024-04-28 14:40:58.855125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec6c72ef03a'
down_revision = 'd2af900ee226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserLikedContent',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('ContentId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ContentId'], ['content.id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('UserId', 'ContentId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserLikedContent')
    # ### end Alembic commands ###
