"""user like content

Revision ID: c7235f3ef8db
Revises: 14105c7cda18
Create Date: 2024-04-27 12:37:59.814838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7235f3ef8db'
down_revision = '14105c7cda18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FamilyFollowing',
    sa.Column('FollowingFamilyId', sa.Integer(), nullable=False),
    sa.Column('FollowedFamilyId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FollowedFamilyId'], ['family.id'], ),
    sa.ForeignKeyConstraint(['FollowingFamilyId'], ['family.id'], ),
    sa.PrimaryKeyConstraint('FollowingFamilyId', 'FollowedFamilyId')
    )
    op.create_table('UserLikedContent',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('ContentId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ContentId'], ['content.id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('UserId', 'ContentId')
    )
    op.drop_table('familyfollowing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('familyfollowing',
    sa.Column('FollowingFamilyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FollowedFamilyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['FollowedFamilyId'], ['family.id'], name='familyfollowing_ibfk_1'),
    sa.ForeignKeyConstraint(['FollowingFamilyId'], ['family.id'], name='familyfollowing_ibfk_2'),
    sa.PrimaryKeyConstraint('FollowingFamilyId', 'FollowedFamilyId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('UserLikedContent')
    op.drop_table('FamilyFollowing')
    # ### end Alembic commands ###
