"""adding cover coulmn to Family

Revision ID: da0bebf1018f
Revises: dff418031aac
Create Date: 2024-05-06 16:29:03.265372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da0bebf1018f'
down_revision = 'dff418031aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coverphoto', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_column('coverphoto')
    # ### end Alembic commands ###
